image: alpine/latest
packages:
  - curl
  - rsync
secrets:
  - f9b0470f-3ea4-4b49-aeb9-99e9f48d75e5 # SSH key for GitHub mirror
  - 2d681c1b-dc07-4222-9d9a-599ec1f3dadc # Pico SSH key for PGS deploy
environment:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: '1'

tasks:
  - configure-ssh: |
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      ssh-keyscan pgs.sh >> ~/.ssh/known_hosts

  - mirror-to-github: |
      cd m1n.land
      git remote add github git@github.com:M1n-74316D65/m1n.land.git || true
      git push --mirror github

  - build: |
      cd m1n.land
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install --frozen-lockfile
      bun run build
      test -d out

  - deploy: |
      cd m1n.land
      PROJECT="land-$(git rev-parse --short HEAD)"
      rsync -rv out/ "pgs.sh:/$PROJECT"
      ssh pgs.sh link land --to "$PROJECT" --write
      ssh pgs.sh retain land -n 3 --write

triggers:
  - action: email
    condition: failure
    to: ~m1n/land@lists.sr.ht

submitter:
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/heads/master
      - 'refs/tags/*'
